# Configuration Settings for ZED-F9K device
# Please change these settings according as necessary
device: /dev/ttyACM0
frame_id: gps
uart1:
  baudrate: 115200
config_on_startup: true
rate: 20                     # in Hz
nav_rate: 1                  # [# of measurement cycles], recommended 1 Hz, may
dgnss_mode: 3                # Fixed mode
dynamic_model: automotive    # automative mode
use_adr: true                # Whether to enable dead reckoning

inf:
  all: false                 # Whether to display all INF messages in console

# Enable necessary u-blox message publishers
publish:
  all: false
  esf:
    meas: true
  nav:
    status: true
    pvt: true
    posecef: false
    hpposllh: true
