// Generated by gencpp from file iahrs_driver/all_data_resetRequest.msg
// DO NOT EDIT!


#ifndef IAHRS_DRIVER_MESSAGE_ALL_DATA_RESETREQUEST_H
#define IAHRS_DRIVER_MESSAGE_ALL_DATA_RESETREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iahrs_driver
{
template <class ContainerAllocator>
struct all_data_resetRequest_
{
  typedef all_data_resetRequest_<ContainerAllocator> Type;

  all_data_resetRequest_()
    {
    }
  all_data_resetRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::iahrs_driver::all_data_resetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iahrs_driver::all_data_resetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct all_data_resetRequest_

typedef ::iahrs_driver::all_data_resetRequest_<std::allocator<void> > all_data_resetRequest;

typedef boost::shared_ptr< ::iahrs_driver::all_data_resetRequest > all_data_resetRequestPtr;
typedef boost::shared_ptr< ::iahrs_driver::all_data_resetRequest const> all_data_resetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iahrs_driver::all_data_resetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iahrs_driver::all_data_resetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace iahrs_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iahrs_driver::all_data_resetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iahrs_driver::all_data_resetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iahrs_driver::all_data_resetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iahrs_driver::all_data_resetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iahrs_driver::all_data_resetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iahrs_driver::all_data_resetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iahrs_driver::all_data_resetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::iahrs_driver::all_data_resetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::iahrs_driver::all_data_resetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iahrs_driver/all_data_resetRequest";
  }

  static const char* value(const ::iahrs_driver::all_data_resetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iahrs_driver::all_data_resetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#This message is used to send command to IAHRS(IMU)\n"
"#All Data Reset command\n"
"\n"
;
  }

  static const char* value(const ::iahrs_driver::all_data_resetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iahrs_driver::all_data_resetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct all_data_resetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iahrs_driver::all_data_resetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::iahrs_driver::all_data_resetRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // IAHRS_DRIVER_MESSAGE_ALL_DATA_RESETREQUEST_H
