// Generated by gencpp from file iahrs_driver/euler_angle_reset.msg
// DO NOT EDIT!


#ifndef IAHRS_DRIVER_MESSAGE_EULER_ANGLE_RESET_H
#define IAHRS_DRIVER_MESSAGE_EULER_ANGLE_RESET_H

#include <ros/service_traits.h>


#include <iahrs_driver/euler_angle_resetRequest.h>
#include <iahrs_driver/euler_angle_resetResponse.h>


namespace iahrs_driver
{

struct euler_angle_reset
{

typedef euler_angle_resetRequest Request;
typedef euler_angle_resetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct euler_angle_reset
} // namespace iahrs_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iahrs_driver::euler_angle_reset > {
  static const char* value()
  {
    return "6b370111df6d9d8116fbdd43bd394a52";
  }

  static const char* value(const ::iahrs_driver::euler_angle_reset&) { return value(); }
};

template<>
struct DataType< ::iahrs_driver::euler_angle_reset > {
  static const char* value()
  {
    return "iahrs_driver/euler_angle_reset";
  }

  static const char* value(const ::iahrs_driver::euler_angle_reset&) { return value(); }
};


// service_traits::MD5Sum< ::iahrs_driver::euler_angle_resetRequest> should match
// service_traits::MD5Sum< ::iahrs_driver::euler_angle_reset >
template<>
struct MD5Sum< ::iahrs_driver::euler_angle_resetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iahrs_driver::euler_angle_reset >::value();
  }
  static const char* value(const ::iahrs_driver::euler_angle_resetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iahrs_driver::euler_angle_resetRequest> should match
// service_traits::DataType< ::iahrs_driver::euler_angle_reset >
template<>
struct DataType< ::iahrs_driver::euler_angle_resetRequest>
{
  static const char* value()
  {
    return DataType< ::iahrs_driver::euler_angle_reset >::value();
  }
  static const char* value(const ::iahrs_driver::euler_angle_resetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iahrs_driver::euler_angle_resetResponse> should match
// service_traits::MD5Sum< ::iahrs_driver::euler_angle_reset >
template<>
struct MD5Sum< ::iahrs_driver::euler_angle_resetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iahrs_driver::euler_angle_reset >::value();
  }
  static const char* value(const ::iahrs_driver::euler_angle_resetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iahrs_driver::euler_angle_resetResponse> should match
// service_traits::DataType< ::iahrs_driver::euler_angle_reset >
template<>
struct DataType< ::iahrs_driver::euler_angle_resetResponse>
{
  static const char* value()
  {
    return DataType< ::iahrs_driver::euler_angle_reset >::value();
  }
  static const char* value(const ::iahrs_driver::euler_angle_resetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IAHRS_DRIVER_MESSAGE_EULER_ANGLE_RESET_H
