// Generated by gencpp from file iahrs_driver/pose_velocity_reset.msg
// DO NOT EDIT!


#ifndef IAHRS_DRIVER_MESSAGE_POSE_VELOCITY_RESET_H
#define IAHRS_DRIVER_MESSAGE_POSE_VELOCITY_RESET_H

#include <ros/service_traits.h>


#include <iahrs_driver/pose_velocity_resetRequest.h>
#include <iahrs_driver/pose_velocity_resetResponse.h>


namespace iahrs_driver
{

struct pose_velocity_reset
{

typedef pose_velocity_resetRequest Request;
typedef pose_velocity_resetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pose_velocity_reset
} // namespace iahrs_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iahrs_driver::pose_velocity_reset > {
  static const char* value()
  {
    return "6b370111df6d9d8116fbdd43bd394a52";
  }

  static const char* value(const ::iahrs_driver::pose_velocity_reset&) { return value(); }
};

template<>
struct DataType< ::iahrs_driver::pose_velocity_reset > {
  static const char* value()
  {
    return "iahrs_driver/pose_velocity_reset";
  }

  static const char* value(const ::iahrs_driver::pose_velocity_reset&) { return value(); }
};


// service_traits::MD5Sum< ::iahrs_driver::pose_velocity_resetRequest> should match
// service_traits::MD5Sum< ::iahrs_driver::pose_velocity_reset >
template<>
struct MD5Sum< ::iahrs_driver::pose_velocity_resetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iahrs_driver::pose_velocity_reset >::value();
  }
  static const char* value(const ::iahrs_driver::pose_velocity_resetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iahrs_driver::pose_velocity_resetRequest> should match
// service_traits::DataType< ::iahrs_driver::pose_velocity_reset >
template<>
struct DataType< ::iahrs_driver::pose_velocity_resetRequest>
{
  static const char* value()
  {
    return DataType< ::iahrs_driver::pose_velocity_reset >::value();
  }
  static const char* value(const ::iahrs_driver::pose_velocity_resetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iahrs_driver::pose_velocity_resetResponse> should match
// service_traits::MD5Sum< ::iahrs_driver::pose_velocity_reset >
template<>
struct MD5Sum< ::iahrs_driver::pose_velocity_resetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iahrs_driver::pose_velocity_reset >::value();
  }
  static const char* value(const ::iahrs_driver::pose_velocity_resetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iahrs_driver::pose_velocity_resetResponse> should match
// service_traits::DataType< ::iahrs_driver::pose_velocity_reset >
template<>
struct DataType< ::iahrs_driver::pose_velocity_resetResponse>
{
  static const char* value()
  {
    return DataType< ::iahrs_driver::pose_velocity_reset >::value();
  }
  static const char* value(const ::iahrs_driver::pose_velocity_resetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IAHRS_DRIVER_MESSAGE_POSE_VELOCITY_RESET_H
