// Generated by gencpp from file iahrs_driver/reboot_sensor.msg
// DO NOT EDIT!


#ifndef IAHRS_DRIVER_MESSAGE_REBOOT_SENSOR_H
#define IAHRS_DRIVER_MESSAGE_REBOOT_SENSOR_H

#include <ros/service_traits.h>


#include <iahrs_driver/reboot_sensorRequest.h>
#include <iahrs_driver/reboot_sensorResponse.h>


namespace iahrs_driver
{

struct reboot_sensor
{

typedef reboot_sensorRequest Request;
typedef reboot_sensorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct reboot_sensor
} // namespace iahrs_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iahrs_driver::reboot_sensor > {
  static const char* value()
  {
    return "6b370111df6d9d8116fbdd43bd394a52";
  }

  static const char* value(const ::iahrs_driver::reboot_sensor&) { return value(); }
};

template<>
struct DataType< ::iahrs_driver::reboot_sensor > {
  static const char* value()
  {
    return "iahrs_driver/reboot_sensor";
  }

  static const char* value(const ::iahrs_driver::reboot_sensor&) { return value(); }
};


// service_traits::MD5Sum< ::iahrs_driver::reboot_sensorRequest> should match
// service_traits::MD5Sum< ::iahrs_driver::reboot_sensor >
template<>
struct MD5Sum< ::iahrs_driver::reboot_sensorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iahrs_driver::reboot_sensor >::value();
  }
  static const char* value(const ::iahrs_driver::reboot_sensorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iahrs_driver::reboot_sensorRequest> should match
// service_traits::DataType< ::iahrs_driver::reboot_sensor >
template<>
struct DataType< ::iahrs_driver::reboot_sensorRequest>
{
  static const char* value()
  {
    return DataType< ::iahrs_driver::reboot_sensor >::value();
  }
  static const char* value(const ::iahrs_driver::reboot_sensorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iahrs_driver::reboot_sensorResponse> should match
// service_traits::MD5Sum< ::iahrs_driver::reboot_sensor >
template<>
struct MD5Sum< ::iahrs_driver::reboot_sensorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iahrs_driver::reboot_sensor >::value();
  }
  static const char* value(const ::iahrs_driver::reboot_sensorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iahrs_driver::reboot_sensorResponse> should match
// service_traits::DataType< ::iahrs_driver::reboot_sensor >
template<>
struct DataType< ::iahrs_driver::reboot_sensorResponse>
{
  static const char* value()
  {
    return DataType< ::iahrs_driver::reboot_sensor >::value();
  }
  static const char* value(const ::iahrs_driver::reboot_sensorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IAHRS_DRIVER_MESSAGE_REBOOT_SENSOR_H
